# docker by using Host network

# FROM node:20
# EXPOSE 8080
# ENV DB_HOST="localhost"
# RUN mkdir /opt/server
# WORKDIR /opt/server
# COPY package.json .
# COPY *.js . 
# RUN npm install
# CMD ["node", "index.js"]

# docker by using bridge network

FROM node:20
EXPOSE 8080
ENV DB_HOST="mysql"
RUN mkdir /opt/server
WORKDIR /opt/server
COPY package.json .
COPY *.js . 
RUN npm install
CMD ["node", "index.js"]


